go: 1.6.3
verbose: false
repository:
    path: github.com/carlpett/zookeeper_exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -s
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/version.BuildDate={{date "20060829-15:04:05"}}
tarball:
    prefix: .
crossbuild:
    platforms:
        - linux/amd64
        - darwin/amd64
        # Below varieties are not enabled due to lack of request and to speed up build times
        # Can be added if needed
        #- darwin/386
        #- linux/386
        #- freebsd/amd64
        #- freebsd/386
        #- windows/amd64
        #- windows/386
        #- openbsd/amd64
        #- openbsd/386
        #- netbsd/amd64
        #- netbsd/386
        #- dragonfly/amd64
        #- linux/arm
        #- linux/arm64
        #- freebsd/arm
        #- openbsd/arm
        #- netbsd/arm
        #- linux/ppc64
        #- linux/ppc64le
        #- linux/mips64
        #- linux/mips64le
